# Importing libraries and dataset

In [28]:
import numpy as np, pandas as pd

dataset = pd.read_csv(r"C:\ML\projects\learning projects\1 car price prediction\dataset.csv")
print(dataset.head())

                                     name   company  year          Price  \
0    Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007         80,000   
1                 Mahindra Jeep CL550 MDI  Mahindra  2006       4,25,000   
2              Maruti Suzuki Alto 800 Vxi    Maruti  2018  Ask For Price   
3  Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014       3,25,000   
4        Ford EcoSport Titanium 1.5L TDCi      Ford  2014       5,75,000   

   kms_driven fuel_type  
0  45,000 kms    Petrol  
1      40 kms    Diesel  
2  22,000 kms    Petrol  
3  28,000 kms    Petrol  
4  36,000 kms    Diesel  


# Exploratory Data Analysis (EDA)

### DATA TYPES

In [29]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB


NOTE: year, price, kms driven should be of float type

#### NULL VALUES

In [30]:
check_null_values = lambda df, column_name: print(f"Null values in '{column_name}':'{df[column_name].isnull().sum()}'") if df[column_name].isnull().any() else print(f"No null values in attribute '{column_name}'")

check_null_values(dataset, 'name')
check_null_values(dataset, 'year')
check_null_values(dataset, 'Price')
check_null_values(dataset, 'kms_driven')
check_null_values(dataset, 'fuel_type')


No null values in attribute 'name'
No null values in attribute 'year'
No null values in attribute 'Price'
Null values in 'kms_driven':'52'
Null values in 'fuel_type':'55'


NOTE: You got sum NULL VALUES IN 'kms_driven' & 'fuel_type'.
We got 2 options now, either to drop the null values or fill them. we fill the null values when the feature having those value have good relation with our dependent variable (y).

#### Unique values

In [31]:
print(dataset['year'].unique())

['2007' '2006' '2018' '2014' '2015' '2012' '2013' '2016' '2010' '2017'
 '2008' '2011' '2019' '2009' '2005' '2000' '...' '150k' 'TOUR' '2003'
 'r 15' '2004' 'Zest' '/-Rs' 'sale' '1995' 'ara)' '2002' 'SELL' '2001'
 'tion' 'odel' '2 bs' 'arry' 'Eon' 'o...' 'ture' 'emi' 'car' 'able' 'no.'
 'd...' 'SALE' 'digo' 'sell' 'd Ex' 'n...' 'e...' 'D...' ', Ac' 'go .'
 'k...' 'o c4' 'zire' 'cent' 'Sumo' 'cab' 't xe' 'EV2' 'r...' 'zest']


NOTE: HAVE INVALID YEAR VALUES

In [32]:
print(dataset['Price'].unique()) 

['80,000' '4,25,000' 'Ask For Price' '3,25,000' '5,75,000' '1,75,000'
 '1,90,000' '8,30,000' '2,50,000' '1,82,000' '3,15,000' '4,15,000'
 '3,20,000' '10,00,000' '5,00,000' '3,50,000' '1,60,000' '3,10,000'
 '75,000' '1,00,000' '2,90,000' '95,000' '1,80,000' '3,85,000' '1,05,000'
 '6,50,000' '6,89,999' '4,48,000' '5,49,000' '5,01,000' '4,89,999'
 '2,80,000' '3,49,999' '2,84,999' '3,45,000' '4,99,999' '2,35,000'
 '2,49,999' '14,75,000' '3,95,000' '2,20,000' '1,70,000' '85,000'
 '2,00,000' '5,70,000' '1,10,000' '4,48,999' '18,91,111' '1,59,500'
 '3,44,999' '4,49,999' '8,65,000' '6,99,000' '3,75,000' '2,24,999'
 '12,00,000' '1,95,000' '3,51,000' '2,40,000' '90,000' '1,55,000'
 '6,00,000' '1,89,500' '2,10,000' '3,90,000' '1,35,000' '16,00,000'
 '7,01,000' '2,65,000' '5,25,000' '3,72,000' '6,35,000' '5,50,000'
 '4,85,000' '3,29,500' '2,51,111' '5,69,999' '69,999' '2,99,999'
 '3,99,999' '4,50,000' '2,70,000' '1,58,400' '1,79,000' '1,25,000'
 '2,99,000' '1,50,000' '2,75,000' '2,85,000' '3,40,00

In [33]:
print(dataset['kms_driven'].unique())

['45,000 kms' '40 kms' '22,000 kms' '28,000 kms' '36,000 kms' '59,000 kms'
 '41,000 kms' '25,000 kms' '24,530 kms' '60,000 kms' '30,000 kms'
 '32,000 kms' '48,660 kms' '4,000 kms' '16,934 kms' '43,000 kms'
 '35,550 kms' '39,522 kms' '39,000 kms' '55,000 kms' '72,000 kms'
 '15,975 kms' '70,000 kms' '23,452 kms' '35,522 kms' '48,508 kms'
 '15,487 kms' '82,000 kms' '20,000 kms' '68,000 kms' '38,000 kms'
 '27,000 kms' '33,000 kms' '46,000 kms' '16,000 kms' '47,000 kms'
 '35,000 kms' '30,874 kms' '15,000 kms' '29,685 kms' '1,30,000 kms'
 '19,000 kms' nan '54,000 kms' '13,000 kms' '38,200 kms' '50,000 kms'
 '13,500 kms' '3,600 kms' '45,863 kms' '60,500 kms' '12,500 kms'
 '18,000 kms' '13,349 kms' '29,000 kms' '44,000 kms' '42,000 kms'
 '14,000 kms' '49,000 kms' '36,200 kms' '51,000 kms' '1,04,000 kms'
 '33,333 kms' '33,600 kms' '5,600 kms' '7,500 kms' '26,000 kms'
 '24,330 kms' '65,480 kms' '28,028 kms' '2,00,000 kms' '99,000 kms'
 '2,800 kms' '21,000 kms' '11,000 kms' '66,000 kms' '3,000 km

NOTE: Have invalid value 'Ask For Price' and need to remove commas 

Note: have invalid value 'Petrol' and 'nan' values

In [34]:
print(dataset['fuel_type'].unique())

['Petrol' 'Diesel' nan 'LPG']


Note: have invalid value 'nan'

### SUMMARY OF EXPLORATORY DATA ANALYSIS (EDA)

## DATA PREPROCESSING

In [35]:
dataset=dataset[dataset['year'].str.isnumeric()]
dataset['year']=dataset['year'].astype(int)

dataset['name']=dataset['name'].str.split(' ').str.slice(0,3).str.join(' ')

dataset['Price']=dataset['Price'].str.replace(',','')
dataset=dataset[dataset['Price'].str.isnumeric()]
dataset['Price']=dataset['Price'].astype(int)


dataset['kms_driven']=dataset['kms_driven'].str.split(' ').str.get(0).str.replace(',','')
dataset=dataset[dataset['kms_driven'].str.isnumeric()]
dataset['kms_driven']=dataset['kms_driven'].astype(int)

dataset= dataset[~dataset['fuel_type'].isna()]

dataset['name']=dataset['name'].str.split(' ').str.slice(0,3).str.join(' ')


In [36]:
#since we have droppend many values we have to re-arrange the index
dataset=dataset.reset_index(drop=True) #dont keep the old index

## checking if all points of EDA were solved

##### NULL VALUES -  STATUS: PASS

In [37]:
check_null_values(dataset, 'name')
check_null_values(dataset, 'year')
check_null_values(dataset, 'Price')
check_null_values(dataset, 'kms_driven')
check_null_values(dataset, 'fuel_type')

No null values in attribute 'name'
No null values in attribute 'year'
No null values in attribute 'Price'
No null values in attribute 'kms_driven'
No null values in attribute 'fuel_type'


##### UNIQUE VALUES -  STATUS: PASS

In [38]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int32 
 3   Price       816 non-null    int32 
 4   kms_driven  816 non-null    int32 
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 28.8+ KB


In [39]:
dataset['year'].unique()

array([2007, 2006, 2014, 2012, 2013, 2016, 2015, 2010, 2017, 2008, 2018,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001])

In [40]:
dataset['Price'].unique()

array([  80000,  425000,  325000,  575000,  175000,  190000,  830000,
        250000,  182000,  315000,  415000,  320000, 1000000,  500000,
        350000,  160000,  310000,   75000,  100000,  290000,   95000,
        180000,  385000,  105000,  650000,  689999,  448000,  549000,
        501000,  489999,  280000,  349999,  284999,  345000,  499999,
        235000,  249999, 1475000,  395000,  220000,  170000,   85000,
        200000,  570000,  110000,  448999, 1891111,  159500,  344999,
        449999,  865000,  699000,  375000,  224999, 1200000,  195000,
        351000,  240000,   90000,  155000,  600000,  189500,  210000,
        390000,  135000, 1600000,  701000,  265000,  525000,  372000,
        635000,  550000,  485000,  329500,  251111,  569999,   69999,
        299999,  399999,  450000,  270000,  158400,  179000,  125000,
        299000,  150000,  285000,  340000,   70000,  289999,  849999,
        749999,  274999,  984999,  599999,  244999,  474999,  245000,
        169500,  275

In [41]:
dataset['kms_driven'].unique()

array([ 45000,     40,  28000,  36000,  41000,  25000,  24530,  60000,
        30000,  32000,  48660,   4000,  16934,  43000,  35550,  39522,
        39000,  55000,  72000,  15975,  70000,  23452,  35522,  48508,
        15487,  82000,  20000,  68000,  38000,  27000,  33000,  46000,
        16000,  47000,  35000,  30874,  15000,  29685, 130000,  19000,
        54000,  13000,  38200,  22000,  50000,  13500,   3600,  45863,
        60500,  12500,  18000,  13349,  29000,  44000,  42000,  14000,
        49000,  36200,  51000, 104000,  33333,  33600,   5600,   7500,
        24330,  65480, 200000,  59000,  99000,   2800,  21000,  11000,
        66000,   3000,   7000,  38500,  37200,  43200,  24800,  45872,
        40000,  11400,  97200,  52000,  31000, 175430,  37000,  65000,
         3350,  75000,  62000,  73000,   2200,  54870,  34580,  97000,
           60,  80200,   3200,      0,   5000,    588,  71200, 175400,
         9300,  56758,  10000,  56450,  56000,  32700,   9000,     73,
      

In [42]:
dataset['fuel_type'].unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

## ALL POINTS OF EDA WERE COVERED SO SAVIG THE CLEANED DATASET

In [43]:
dataset.to_csv(r'C:\ML\projects\learning projects\1 car price prediction\cleaned_dataset.csv')

# Model fitting

## DATA splitting

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
x=dataset.drop(columns='Price')
y=dataset['Price']

In [46]:
xtrain, xtest, ytrain, ytest= train_test_split(x,y,test_size=0.2)

## Categorical data handling

In [47]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer

onehot=OneHotEncoder()
onehot.fit(x[['name','company','fuel_type']])

column_tran=make_column_transformer(
    (OneHotEncoder(categories=onehot.categories_),['name','company','fuel_type']),
    remainder='passthrough'
    )


## PIPELINE OF MODEL

In [48]:
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression

model= LinearRegression()
pipeline=make_pipeline(column_tran,model)
pipeline.fit(xtrain,ytrain)
ypred=pipeline.predict(xtest)

In [49]:
from sklearn.metrics import r2_score
r2_score(ytest,ypred)

0.21422833648088402

## best train_test_split RANDOM STATE

In [50]:
# #Finding the model with a random state of TrainTestSplit witth greatest score
# #REMOVE AFTER USE
# scores=[]
# for i in range(1000):
#     X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=i)
#     lr=LinearRegression()
#     pipe=make_pipeline(column_tran,lr)
#     pipe.fit(X_train,y_train)
#     y_pred=pipe.predict(X_test)
#     scores.append(r2_score(y_test,y_pred))

# print('greatest score is given by i=',np.argmax(scores),'with score of ',scores[np.argmax(scores)])

In [51]:
# X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=np.argmax(scores))
# lr=LinearRegression()
# pipe=make_pipeline(column_tran,lr)
# pipe.fit(X_train,y_train)
# y_pred=pipe.predict(X_test)
# r2_score(y_test,y_pred)

## Predictions

In [52]:
output=pipeline.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

print(output)

[426542.70589308]
